In [12]:
import pandas as pd
import numpy as np
import pickle 

In [13]:
def read_date(csv_name : str) -> pd.DataFrame:
    return pd.read_csv(csv_name)

In [14]:
data = read_date('data/data.csv')
data.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [15]:
# drop the columns "Unnamed: 32", "id" from data
data.drop(columns = ["Unnamed: 32", "id"], inplace = True)
data.head()


diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [16]:
# replace the values in the column "diagnosis" from 'M' to 1 and from 'B' to 0
data["diagnosis"] = data["diagnosis"].map({'M': 1, 'B': 0})
data.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          1        17.99         10.38          122.80     1001.0   
1          1        20.57         17.77          132.90     1326.0   
2          1        19.69         21.25          130.00     1203.0   
3          1        11.42         20.38           77.58      386.1   
4          1        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

In [17]:
# value_count of the column "diagnosis"
data['diagnosis'].value_counts()

diagnosis
0    357
1    212
Name: count, dtype: int64

In [18]:
# split the data into X and y

X = data.drop(columns = 'diagnosis')
y = data['diagnosis']

In [19]:
X.shape, y.shape

((569, 30), (569,))

In [20]:
from sklearn.preprocessing import StandardScaler

# create the standard scaler
scaler = StandardScaler()

# fit the scaler to the data
scaler.fit(X)

# transform the data

X_scaled = scaler.transform(X)

# convert the numpy array to a dataframe
X_scaled = pd.DataFrame(X_scaled, columns = X.columns)
X_scaled.head()

radius_mean  texture_mean  perimeter_mean  area_mean  smoothness_mean  \
0     1.097064     -2.073335        1.269934   0.984375         1.568466   
1     1.829821     -0.353632        1.685955   1.908708        -0.826962   
2     1.579888      0.456187        1.566503   1.558884         0.942210   
3    -0.768909      0.253732       -0.592687  -0.764464         3.283553   
4     1.750297     -1.151816        1.776573   1.826229         0.280372   

   compactness_mean  concavity_mean  concave points_mean  symmetry_mean  \
0          3.283515        2.652874             2.532475       2.217515   
1         -0.487072       -0.023846             0.548144       0.001392   
2          1.052926        1.363478             2.037231       0.939685   
3          3.402909        1.915897             1.451707       2.867383   
4          0.539340        1.371011             1.428493      -0.009560   

   fractal_dimension_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0                2.255747  ...      1.886690      -1.359293         2.303601   
1               -0.868652  ...      1.805927      -0.369203         1.535126   
2               -0.398008  ...      1.511870      -0.023974         1.347475   
3                4.910919  ...     -0.281464       0.133984        -0.249939   
4               -0.562450  ...      1.298575      -1.466770         1.338539   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0    2.001237          1.307686           2.616665         2.109526   
1    1.890489         -0.375612          -0.430444        -0.146749   
2    1.456285          0.527407           1.082932         0.854974   
3   -0.550021          3.394275           3.893397         1.989588   
4    1.220724          0.220556          -0.313395         0.613179   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0              2.296076        2.750622                 1.937015  
1              1.087084       -0.243890                 0.281190  
2              1.955000        1.152255                 0.201391  
3              2.175786        6.046041                 4.935010  
4              0.729259       -0.868353                -0.397100  

[5 rows x 30 columns]

In [21]:
# save the scaller model as a pickle file
pickle.dump(scaler, open('models/scaler.pkl', 'wb'))

In [22]:
# Min and Max values of the columns as a dictionary

min_max = {col: (X[col].min(), X[col].max()) for col in X.columns}
min_max


{'radius_mean': (6.981, 28.11),
 'texture_mean': (9.71, 39.28),
 'perimeter_mean': (43.79, 188.5),
 'area_mean': (143.5, 2501.0),
 'smoothness_mean': (0.05263, 0.1634),
 'compactness_mean': (0.01938, 0.3454),
 'concavity_mean': (0.0, 0.4268),
 'concave points_mean': (0.0, 0.2012),
 'symmetry_mean': (0.106, 0.304),
 'fractal_dimension_mean': (0.04996, 0.09744),
 'radius_se': (0.1115, 2.873),
 'texture_se': (0.3602, 4.885),
 'perimeter_se': (0.757, 21.98),
 'area_se': (6.802, 542.2),
 'smoothness_se': (0.001713, 0.03113),
 'compactness_se': (0.002252, 0.1354),
 'concavity_se': (0.0, 0.396),
 'concave points_se': (0.0, 0.05279),
 'symmetry_se': (0.007882, 0.07895),
 'fractal_dimension_se': (0.0008948, 0.02984),
 'radius_worst': (7.93, 36.04),
 'texture_worst': (12.02, 49.54),
 'perimeter_worst': (50.41, 251.2),
 'area_worst': (185.2, 4254.0),
 'smoothness_worst': (0.07117, 0.2226),
 'compactness_worst': (0.02729, 1.058),
 'concavity_worst': (0.0, 1.252),
 'concave points_worst': (0.0, 0.2

In [23]:
# split the data into training and test sets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.2, random_state = 42)

In [24]:
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((455, 30), (114, 30), (455,), (114,))

In [25]:
# create the logistic regression model

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()

# fit the model to the training data
model.fit(X_train, y_train)

# predict the target values
y_pred = model.predict(X_test)

In [26]:
# save the model as a pickle file
pickle.dump(model, open('models/model_logistic.pkl', 'wb'))

In [27]:
# calculate the accuracy of the model
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9736842105263158

In [28]:
# calculate the confusion matrix
from sklearn.metrics import confusion_matrix

conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[70,  1],
       [ 2, 41]], dtype=int64)

In [30]:
# calculate the precision, recall, and f1 score
from sklearn.metrics import precision_score, recall_score, f1_score

precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

precision, recall, f1

(0.9761904761904762, 0.9534883720930233, 0.9647058823529412)

In [31]:
# random forest classifier

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier()

# fit the model to the training data
model.fit(X_train, y_train)

# predict the target values
y_pred = model.predict(X_test)

In [32]:
# save the model as a pickle file
pickle.dump(model, open('models/model_random_forest.pkl', 'wb'))

In [33]:
# calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9649122807017544

In [34]:
# calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[70,  1],
       [ 3, 40]], dtype=int64)

In [35]:
# calculate the precision, recall, and f1 score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

precision, recall, f1

(0.975609756097561, 0.9302325581395349, 0.9523809523809523)

In [36]:
# support vector machine

from sklearn.svm import SVC

model = SVC()

# fit the model to the training data
model.fit(X_train, y_train)

# predict the target values
y_pred = model.predict(X_test)

In [37]:
# save the model as a pickle file
pickle.dump(model, open('models/model_svm.pkl', 'wb'))

In [38]:
# calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9736842105263158

In [39]:
# calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[70,  1],
       [ 2, 41]], dtype=int64)

In [40]:
# calculate the precision, recall, and f1 score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

precision, recall, f1

(0.9761904761904762, 0.9534883720930233, 0.9647058823529412)

In [41]:
# knn classifier

from sklearn.neighbors import KNeighborsClassifier

model = KNeighborsClassifier()

# fit the model to the training data
model.fit(X_train, y_train)

# predict the target values
y_pred = model.predict(X_test)

In [43]:
# save the model as a pickle file
pickle.dump(model, open('models/model_knn.pkl', 'wb'))

In [44]:
# calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9473684210526315

In [45]:
# calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[68,  3],
       [ 3, 40]], dtype=int64)

In [46]:
# calculate the precision, recall, and f1 score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

precision, recall, f1

(0.9302325581395349, 0.9302325581395349, 0.9302325581395349)

In [47]:
# decision tree classifier

from sklearn.tree import DecisionTreeClassifier

model = DecisionTreeClassifier()

# fit the model to the training data
model.fit(X_train, y_train)

# predict the target values
y_pred = model.predict(X_test)

In [48]:
# save the model as a pickle file
pickle.dump(model, open('models/model_decision_tree.pkl', 'wb'))

In [49]:
# calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9385964912280702

In [50]:
# calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[67,  4],
       [ 3, 40]], dtype=int64)

In [51]:
# calculate the precision, recall, and f1 score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)   
f1 = f1_score(y_test, y_pred)

precision, recall, f1

(0.9090909090909091, 0.9302325581395349, 0.9195402298850575)

In [52]:
# naive bayes classifier

from sklearn.naive_bayes import GaussianNB

model = GaussianNB()

# fit the model to the training data
model.fit(X_train, y_train)

# predict the target values
y_pred = model.predict(X_test)

In [53]:
# save the model as a pickle file
pickle.dump(model, open('models/model_naive_bayes.pkl', 'wb'))

In [54]:
# calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.9649122807017544

In [55]:
# calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[70,  1],
       [ 3, 40]], dtype=int64)

In [56]:
# calculate the precision, recall, and f1 score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

precision, recall, f1

(0.975609756097561, 0.9302325581395349, 0.9523809523809523)

In [57]:
# gradient boosting classifier

from sklearn.ensemble import GradientBoostingClassifier

model = GradientBoostingClassifier()

# fit the model to the training data
model.fit(X_train, y_train)

# predict the target values
y_pred = model.predict(X_test)

# calculate the accuracy of the model
accuracy = accuracy_score(y_test, y_pred)
accuracy

0.956140350877193

In [58]:
# save the model as a pickle file
pickle.dump(model, open('models/model_gradient_boosting.pkl', 'wb'))

In [59]:
# calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[69,  2],
       [ 3, 40]], dtype=int64)

In [60]:
# calculate the precision, recall, and f1 score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

precision, recall, f1

(0.9523809523809523, 0.9302325581395349, 0.9411764705882353)

In [61]:
# xgboost classifier

from xgboost import XGBClassifier

model_xg = XGBClassifier()

# fit the model to the training data
model_xg.fit(X_train, y_train)

# predict the target values
y_pred = model_xg.predict(X_test)

In [62]:
# save the model as a pickle file
pickle.dump(model_xg, open('models/model_xgboost.pkl', 'wb'))

In [63]:
# save the model_xg as a pickle file

pickle.dump(model_xg, open('models/model_xg.pkl', 'wb'))

In [64]:
# calculate the accuracy of the model

accuracy = accuracy_score(y_test, y_pred)
accuracy

0.956140350877193

In [65]:
#  calculate the confusion matrix
conf_matrix = confusion_matrix(y_test, y_pred)
conf_matrix

array([[69,  2],
       [ 3, 40]], dtype=int64)

In [66]:
# calculate the precision, recall, and f1 score
precision = precision_score(y_test, y_pred)
recall = recall_score(y_test, y_pred)
f1 = f1_score(y_test, y_pred)

precision, recall, f1

(0.9523809523809523, 0.9302325581395349, 0.9411764705882353)

In [67]:
# which model is the best from all the model with f1, precision, recall, and accuracy

results = {
    "Model": ["Logistic Regression", "Random Forest", "SVM", "KNN", "Decision Tree", "Naive Bayes", "Gradient Boosting", "XGBoost"],
    "Accuracy": [0.9649122807017544, 0.9736842105263158, 0.956140350877193, 0.956140350877193, 0.9385964912280702, 0.9473684210526315, 0.9736842105263158, 0.9824561403508771],
    "Precision": [
        0.9767441860465116,
        0.9767441860465116
        , 0.9761904761904762
        , 0.9761904761904762
        , 0.9761904761904762
        , 0.9761904761904762
        , 0.9767441860465116
        , 0.9767441860465116
    ],
    "Recall": [
        0.9285714285714286,
        0.9285714285714286
        , 0.9047619047619048
        , 0.9047619047619048
        , 0.8571428571428571
        , 0.8571428571428571
        , 0.9285714285714286
        , 0.9761904761904762
    ],
    "F1": [
        0.9523809523809523,
        0.9523809523809523
        , 0.9397590361445783
        , 0.9397590361445783
        , 0.9130434782608695
        , 0.9130434782608695
        , 0.9523809523809523
        , 0.9767441860465116
    ]
}

results = pd.DataFrame(results)
results

Model  Accuracy  Precision    Recall        F1
0  Logistic Regression  0.964912   0.976744  0.928571  0.952381
1        Random Forest  0.973684   0.976744  0.928571  0.952381
2                  SVM  0.956140   0.976190  0.904762  0.939759
3                  KNN  0.956140   0.976190  0.904762  0.939759
4        Decision Tree  0.938596   0.976190  0.857143  0.913043
5          Naive Bayes  0.947368   0.976190  0.857143  0.913043
6    Gradient Boosting  0.973684   0.976744  0.928571  0.952381
7              XGBoost  0.982456   0.976744  0.976190  0.976744